// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACvgz9v2dygEOR-nzExytEaXgv0L7Tzy0',
    appId: '1:925296035017:web:3f108965da0962d9e9f918',
    messagingSenderId: '925296035017',
    projectId: 'spotreport-920a5',
    authDomain: 'spotreport-920a5.firebaseapp.com',
    storageBucket: 'spotreport-920a5.firebasestorage.app',
    measurementId: 'G-08Q4LSP6WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCXI8Nub7XBtDnNXxettKkEDVbtGhjaUo',
    appId: '1:925296035017:android:e47194191e4ead14e9f918',
    messagingSenderId: '925296035017',
    projectId: 'spotreport-920a5',
    storageBucket: 'spotreport-920a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDiVaygnvPt5ex8Vo28w1erZnP5deUsII',
    appId: '1:925296035017:ios:540aa5df3c5cc3f7e9f918',
    messagingSenderId: '925296035017',
    projectId: 'spotreport-920a5',
    storageBucket: 'spotreport-920a5.firebasestorage.app',
    iosBundleId: 'com.example.mvp',
  );
}
